"use client";
import { useState, type ElementType } from "react";
import { ArrowRight, Bot, Check, ChevronDown, FileText, HeartPulse, Landmark, Languages, Menu, Mic, Search, Send, ShieldCheck, Sparkles, Volume2, Wheat, X, GraduationCap, House, CircleHelp, MapPin, ChevronRight, Download, Save, Info, Users, Sun, Moon, LogIn, LogOut, UserRound, BriefcaseBusiness } from "lucide-react";

type Scheme={name:string; dept:string; category:string; match:number; benefit:string; eligibility:string; docs:string[]; icon:ElementType; color:string};
const schemes:Scheme[]=[
 {name:"PM-KISAN",dept:"Ministry of Agriculture",category:"Agriculture",match:92,benefit:"₹6,000 annual income support for eligible farmer families.",eligibility:"Small and marginal farmer family with cultivable land.",docs:["Aadhaar Card","Land ownership record","Bank account details"],icon:Wheat,color:"bg-emerald-50 text-emerald-700"},
 {name:"Ayushman Bharat PM-JAY",dept:"Ministry of Health",category:"Healthcare",match:84,benefit:"Health cover up to ₹5 lakh per family per year.",eligibility:"Eligible family listed under applicable government criteria.",docs:["Aadhaar Card","Ration card","Family ID"],icon:HeartPulse,color:"bg-rose-50 text-rose-700"},
 {name:"PM Awas Yojana",dept:"Ministry of Housing",category:"Housing",match:78,benefit:"Assistance for a safe, permanent home.",eligibility:"Households meeting rural or urban housing criteria.",docs:["Aadhaar Card","Income certificate","Residence proof"],icon:House,color:"bg-amber-50 text-amber-700"},
 {name:"Beti Bachao, Beti Padhao",dept:"Ministry of Women & Child",category:"Women & Child",match:75,benefit:"Support and awareness for girl child education and empowerment.",eligibility:"Families with a girl child; benefits vary by state.",docs:["Birth certificate","Aadhaar Card","Bank account details"],icon:GraduationCap,color:"bg-violet-50 text-violet-700"},
 {name:"PM Fasal Bima Yojana",dept:"Ministry of Agriculture",category:"Agriculture",match:88,benefit:"Crop insurance support against notified crop losses.",eligibility:"Farmers growing notified crops in participating areas.",docs:["Aadhaar Card","Land or crop details","Bank account details"],icon:Wheat,color:"bg-emerald-50 text-emerald-700"},
 {name:"Kisan Credit Card",dept:"Ministry of Agriculture",category:"Financial Assistance",match:85,benefit:"Affordable short-term credit support for farming needs.",eligibility:"Eligible farmers and allied agricultural activity holders.",docs:["Aadhaar Card","Land record","Bank details"],icon:Landmark,color:"bg-emerald-50 text-emerald-700"},
 {name:"MGNREGA",dept:"Ministry of Rural Development",category:"Employment",match:86,benefit:"Demand-based wage employment in rural areas.",eligibility:"Adult members of rural households willing to do unskilled manual work.",docs:["Aadhaar Card","Job card","Bank account details"],icon:Users,color:"bg-sky-50 text-sky-700"},
 {name:"PM Mudra Yojana",dept:"Ministry of Finance",category:"Financial Assistance",match:81,benefit:"Collateral-free business loan support through eligible lenders.",eligibility:"Small businesses and non-corporate enterprises meeting lender criteria.",docs:["Aadhaar Card","Business plan","Bank account details"],icon:Landmark,color:"bg-blue-50 text-blue-700"},
 {name:"PM Vishwakarma",dept:"Ministry of MSME",category:"Employment",match:79,benefit:"Skill, toolkit and credit support for eligible traditional artisans.",eligibility:"Artisans and craftspeople in notified traditional trades.",docs:["Aadhaar Card","Occupation details","Bank account details"],icon:BriefcaseBusiness,color:"bg-orange-50 text-orange-700"},
 {name:"National Scholarship Portal",dept:"Ministry of Education",category:"Education",match:82,benefit:"Central and state scholarship discovery for eligible students.",eligibility:"Students meeting the relevant scholarship’s academic and income rules.",docs:["Aadhaar Card","Income certificate","Academic documents"],icon:GraduationCap,color:"bg-violet-50 text-violet-700"},
 {name:"PM Poshan",dept:"Ministry of Education",category:"Education",match:77,benefit:"Nutritional support for children in eligible government and aided schools.",eligibility:"Children enrolled in covered schools under the programme.",docs:["School ID","Student record","Parent/guardian details"],icon:GraduationCap,color:"bg-violet-50 text-violet-700"},
 {name:"Pradhan Mantri Matru Vandana Yojana",dept:"Ministry of Women & Child",category:"Women & Child",match:83,benefit:"Maternity benefit support for eligible mothers.",eligibility:"Eligibility depends on current programme guidelines and beneficiary category.",docs:["Aadhaar Card","Pregnancy registration","Bank account details"],icon:HeartPulse,color:"bg-rose-50 text-rose-700"},
 {name:"Sukanya Samriddhi Account",dept:"Department of Posts",category:"Women & Child",match:80,benefit:"Long-term savings account for a girl child.",eligibility:"Parent or guardian of an eligible girl child, subject to account rules.",docs:["Birth certificate","Guardian ID","Address proof"],icon:GraduationCap,color:"bg-pink-50 text-pink-700"},
 {name:"Atal Pension Yojana",dept:"Ministry of Finance",category:"Social Security",match:74,benefit:"Contributory pension support for eligible subscribers.",eligibility:"Indian citizens meeting age, banking and scheme conditions.",docs:["Aadhaar Card","Bank account details","Mobile number"],icon:ShieldCheck,color:"bg-indigo-50 text-indigo-700"},
 {name:"PM Suraksha Bima Yojana",dept:"Ministry of Finance",category:"Insurance",match:76,benefit:"Low-cost accident insurance cover through eligible bank accounts.",eligibility:"Eligible bank account holders within the prescribed age range.",docs:["Aadhaar Card","Bank account details","Consent form"],icon:ShieldCheck,color:"bg-indigo-50 text-indigo-700"},
 {name:"PM Jeevan Jyoti Bima Yojana",dept:"Ministry of Finance",category:"Insurance",match:73,benefit:"Renewable life insurance cover through eligible bank accounts.",eligibility:"Eligible account holders within the prescribed age range.",docs:["Aadhaar Card","Bank account details","Consent form"],icon:ShieldCheck,color:"bg-indigo-50 text-indigo-700"},
 {name:"PM Ujjwala Yojana",dept:"Ministry of Petroleum",category:"Women & Child",match:80,benefit:"LPG connection support for eligible households.",eligibility:"Adult women from eligible households under current scheme criteria.",docs:["Aadhaar Card","Ration card","Bank account details"],icon:HeartPulse,color:"bg-rose-50 text-rose-700"},
 {name:"Swachh Bharat Mission (Gramin)",dept:"Ministry of Jal Shakti",category:"Housing",match:72,benefit:"Support for sanitation facilities under applicable local guidelines.",eligibility:"Rural households meeting the relevant programme requirements.",docs:["Aadhaar Card","Residence certificate","Household details"],icon:House,color:"bg-amber-50 text-amber-700"},
];
const profileKeywords:{terms:string[]; schemes:string[]; summary:string}[]=[
 {terms:["farmer","farming","kisan","किसान","खेती","agriculture","land"],schemes:["PM-KISAN","PM Awas Yojana","Ayushman Bharat PM-JAY"],summary:"You mentioned farming. Support for eligible farmer families, housing and health protection may be relevant."},
 {terms:["student","education","school","college","पढ़ाई","छात्र","बच्चे","children","girl","daughter","बेटी"],schemes:["Beti Bachao, Beti Padhao","Ayushman Bharat PM-JAY","PM Awas Yojana"],summary:"You mentioned education or children. Women & child support, health cover and household support may be relevant."},
 {terms:["health","hospital","illness","medical","बीमारी","इलाज","hospital"],schemes:["Ayushman Bharat PM-JAY","PM Awas Yojana"],summary:"You mentioned a health need. Ayushman Bharat may be relevant for eligible families."},
 {terms:["house","housing","home","rent","घर","आवास","homeless"],schemes:["PM Awas Yojana","Ayushman Bharat PM-JAY"],summary:"You mentioned a housing need. PM Awas Yojana may be a potential match if your household meets the applicable criteria."},
 {terms:["low income","poor","income","गरीब","कम आय","rural","village","गांव","woman","women","महिला","widow"],schemes:["Ayushman Bharat PM-JAY","PM Awas Yojana","Beti Bachao, Beti Padhao"],summary:"Based on the income, rural or family details shared, these benefits may be worth checking."},
 {terms:["job","unemployed","employment","work","रोजगार","नौकरी","काम","artisan","business","shop"],schemes:["MGNREGA","PM Mudra Yojana","PM Vishwakarma"],summary:"You mentioned work, employment or a business need. These employment and livelihood schemes may be relevant."},
 {terms:["pregnant","maternity","pregnancy","mother","delivery","गर्भवती","मातृत्व"],schemes:["Pradhan Mantri Matru Vandana Yojana","PM Ujjwala Yojana","Ayushman Bharat PM-JAY"],summary:"You mentioned maternity or maternal health. These potential maternal and household-support benefits may be relevant."},
 {terms:["insurance","pension","old age","senior","elderly","बीमा","पेंशन","बुजुर्ग"],schemes:["Atal Pension Yojana","PM Suraksha Bima Yojana","PM Jeevan Jyoti Bima Yojana"],summary:"You mentioned insurance, pension or senior-citizen needs. These social-security options may be worth checking."},
];
function findMatches(question:string){const normalized=question.toLowerCase();const hits=profileKeywords.filter(r=>r.terms.some(term=>normalized.includes(term.toLowerCase())));const names=hits.length?Array.from(new Set(hits.flatMap(r=>r.schemes))):schemes.map(s=>s.name);const summary=hits.length===1?hits[0].summary:hits.length>1?"I combined the family, income, occupation and need details you shared to find the most relevant potential benefits.":"I found broad potential matches. Add your occupation, state, income range or family details for more precise guidance.";return {items:names.map(name=>schemes.find(s=>s.name===name)!).filter(Boolean),summary}}
const faqs=["What is Vaani-Setu?","How does Vaani-Setu find relevant schemes?","Which languages are supported?","Does Vaani-Setu guarantee eligibility?","Does Vaani-Setu submit applications?","How is citizen information handled?"];
function SchemeCard({s,compact=false}:{s:Scheme;compact?:boolean}){const Icon=s.icon; return <article className="scheme-card"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className={`icon-box ${s.color}`}><Icon size={21}/></div><div><p className="text-xs font-semibold text-slate-500">{s.dept}</p><h3 className="font-bold text-ink">{s.name}</h3></div></div><span className="match">{s.match}% match</span></div><p className="mt-4 text-sm leading-6 text-slate-600">{s.benefit}</p>{!compact&&<><div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600"><b className="text-ink">Potential eligibility:</b> {s.eligibility}</div><div className="mt-4 flex gap-2"><button className="small-btn primary">Check eligibility</button><button className="small-btn">View details</button></div><p className="mt-3 flex items-center gap-1 text-[11px] text-slate-400"><Info size={12}/> Verify on official government portal</p></>}</article>}
function VoiceOrb({listening,onClick}:{listening:boolean;onClick:()=>void}){return <button onClick={onClick} aria-label="Start voice conversation" className={`voice-orb ${listening?"is-listening":""}`}><span className="rings"/><Mic size={28}/></button>}
export default function Home(){
 const [menu,setMenu]=useState(false),[lang,setLang]=useState("हिन्दी"),[listening,setListening]=useState(false),[input,setInput]=useState("I am a farmer with low income. What government schemes can help me?"),[messages,setMessages]=useState([{role:"ai",text:"नमस्ते! मैं आपकी जानकारी समझकर सही सरकारी योजनाएँ खोजने में मदद करूँगी।"}]),[typing,setTyping]=useState(false),[faq,setFaq]=useState<number|null>(null),[step,setStep]=useState(1),[toast,setToast]=useState(""),[dark,setDark]=useState(false),[loginOpen,setLoginOpen]=useState(false),[loggedIn,setLoggedIn]=useState(false),[name,setName]=useState(""),[matchedSchemes,setMatchedSchemes]=useState(schemes.slice(0,3)),[matchSummary,setMatchSummary]=useState("Share your situation to discover potential benefits."),[page,setPage]=useState("home");
 const send=()=>{if(!input.trim())return;const question=input;setMessages(m=>[...m,{role:"user",text:question}]);setInput("");setTyping(true);setTimeout(()=>{const result=findMatches(question);setMatchedSchemes(result.items);setMatchSummary(result.summary);setTyping(false);setMessages(m=>[...m,{role:"ai",text:`${result.summary} I found ${result.items.length} potential scheme match${result.items.length===1?"":"es"}. Review the eligibility and documents shown alongside.`}])},750)};
 const voice=()=>{
  if(listening){setListening(false);return}
  const SpeechRecognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;
  if(SpeechRecognition){
   const recognition=new SpeechRecognition(); recognition.lang=lang==="English"?"en-IN":"hi-IN"; recognition.interimResults=false;
   recognition.onstart=()=>setListening(true); recognition.onresult=(event:any)=>{setInput(event.results[0][0].transcript);setListening(false)};
   recognition.onerror=()=>setListening(false); recognition.onend=()=>setListening(false); recognition.start();
  } else { setListening(true); setTimeout(()=>setListening(false),2500) }
 };
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
 const login=()=>{if(!name.trim()){notify("Please enter your name to continue.");return}setLoggedIn(true);setLoginOpen(false);notify(`Welcome, ${name.trim()}!`)};
 const go=(next:string)=>{setPage(next);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className={`${dark?"dark ":""}view-${page}`}>
 <nav className="nav"><button onClick={()=>go("home")} className="brand"><span className="brandmark"><Volume2 size={18}/></span>VAANI-SETU</button><div className={`navlinks ${menu?"open":""}`}><button onClick={()=>go("assistant")}>AI Assistant</button><button onClick={()=>go("schemes")}>Schemes</button><button onClick={()=>go("eligibility")}>Eligibility</button><button onClick={()=>go("guidance")}>Guidance</button><button onClick={()=>go("about")}>About</button></div><div className="navright"><select value={lang} onChange={e=>setLang(e.target.value)} aria-label="Language"><option>हिन्दी</option><option>English</option><option>বাংলা</option><option>मराठी</option><option>தமிழ்</option></select><button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label="Toggle day and night theme" title="Toggle theme">{dark?<Sun size={17}/>:<Moon size={17}/>}</button>{loggedIn?<button className="user-button" onClick={()=>{setLoggedIn(false);notify("You have been logged out.")}} title="Log out"><UserRound size={16}/><span>{name || "Citizen"}</span><LogOut size={15}/></button>:<button className="login-button" onClick={()=>setLoginOpen(true)}><LogIn size={16}/> Log in</button>}<button onClick={()=>go("assistant")} className="cta">Try Vaani-Setu <ArrowRight size={16}/></button><button className="menub" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></nav>
 <section id="home" className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15}/> AI for inclusive public services</div><h1>One Conversation.<br/><em>Every Government Benefit.</em></h1><p>Tell us about your situation in your own language. Vaani-Setu uses AI to discover relevant government schemes, explain eligibility, and guide your next steps.</p><div className="hero-actions"><button className="cta big" onClick={()=>go("assistant")}><Mic size={18}/> Start a conversation</button><button className="outline big" onClick={()=>go("schemes")}>Explore schemes <ArrowRight size={17}/></button></div><div className="trust"><ShieldCheck size={20}/><span>Private by design <b>·</b> Guidance, not a guarantee <b>·</b> Built for every citizen</span></div></div>
 <div className="hero-ai"><div className="ai-top"><div className="ai-avatar"><Bot size={21}/></div><div><b>Vaani Assistant</b><p><span className="online"/> Ready to help in {lang}</p></div><Languages size={19} className="ml-auto text-slate-400"/></div><div className="bubble citizen">मेरे दो बच्चे हैं, मैं गांव में रहती हूं और मेरी आय कम है। मुझे कौन-कौन सी सरकारी योजनाओं का लाभ मिल सकता है?</div><div className="bubble ai">आपकी जानकारी के आधार पर कुछ सरकारी योजनाएँ आपके लिए प्रासंगिक हो सकती हैं। आइए आपकी eligibility को समझते हैं।</div><div className="listening"><div className="wave">{[1,2,3,4,5,6,7,8,9].map(i=><i key={i} style={{animationDelay:`${i*.08}s`}}/>)}</div><span>{listening?"Listening…":"Tap to start speaking"}</span><VoiceOrb listening={listening} onClick={voice}/></div><div className="ai-input">Ask Vaani anything… <Send size={18}/></div></div></section>
 <section className="problem"><div className="center intro"><span className="section-tag">THE CHALLENGE</span><h2>The information exists. <em>The access layer is broken.</em></h2><p>Millions of citizens miss out on benefits simply because the journey is too hard to begin.</p></div><div className="problem-grid">{[[Search,"Scattered information","Scheme information is spread across multiple portals and sources."],[CircleHelp,"Complex eligibility","Rules and requirements are difficult to understand."],[Languages,"Language barriers","Important information isn't always accessible in local languages."],[Users,"Dependence on intermediaries","Citizens can depend on middlemen for guidance."]].map(([I,t,d]:any)=><div className="problem-card" key={t}><I/><h3>{t}</h3><p>{d}</p></div>)}</div><div className="lost-flow"><span>Eligible citizen</span><ChevronRight/><span>Doesn’t know</span><ChevronRight/><span>Can’t understand</span><ChevronRight/><span>Doesn’t apply</span><ChevronRight/><b>Benefit lost</b></div></section>
 <section id="how" className="solution"><div><span className="section-tag">THE SOLUTION</span><h2>Meet <em>Vaani-Setu</em></h2><p className="lead">A conversational AI bridge between citizens and government schemes.</p></div><div className="feature-list">{[["01","Speak naturally","Describe your life situation in the language you’re most comfortable with.",Mic],["02","Understand the citizen","AI extracts relevant context such as income, location and priorities.",Bot],["03","Match relevant schemes","Find schemes that may fit a citizen’s profile.",Landmark],["04","Explain eligibility","Turn complex rules into clear, simple explanations.",Check],["05","Guide the application","Get document checklists and clear next steps.",FileText]].map(([n,t,d,I]:any)=><div className="feature" key={n}><span>{n}</span><div className="feature-icon"><I size={20}/></div><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></section>
 <section id="assistant" className="demo"><div className="center intro"><span className="section-tag">LIVE PROTOTYPE</span><h2>Try the <em>Vaani-Setu AI Assistant</em></h2><p>Ask naturally. Get potential benefits, clear explanations, and a path forward.</p></div><div className="demo-grid"><div className="chat"><div className="panel-head"><div className="ai-avatar"><Bot size={20}/></div><div><b>Vaani Assistant</b><p>Guidance in {lang}</p></div><span className="safe">Safe demo</span></div><div className="chat-body">{messages.map((m,i)=><div key={i} className={`chat-msg ${m.role}`}>{m.text}</div>)}{typing&&<div className="chat-msg ai dots"><i/><i/><i/></div>}</div><div className="chat-compose"><button onClick={voice} className={listening?"mic-active":""}><Mic size={18}/></button><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="e.g. I am a farmer with low income…"/><button className="send" onClick={send}><Send size={17}/></button></div></div><aside className="matches"><div className="match-head"><div><p>YOUR POTENTIAL MATCHES</p><h3>Personalized for you</h3></div><Sparkles className="text-saffron"/></div><p className="match-summary">{matchSummary}</p>{matchedSchemes.map(s=><SchemeCard s={s} compact key={s.name}/>)}<button className="viewall" onClick={()=>document.getElementById("schemes")?.scrollIntoView({behavior:"smooth"})}>View all matches <ArrowRight size={16}/></button></aside></div></section>
 <section id="schemes" className="dashboard"><div className="section-top"><div><span className="section-tag">DISCOVER BENEFITS</span><h2>Find government <em>schemes for you.</em></h2></div><button className="outline" onClick={()=>notify("Filters updated with your preferences.")}><Search size={16}/> Search schemes</button></div><div className="filters"><MapPin size={17}/><select><option>All States</option><option>Maharashtra</option><option>Uttar Pradesh</option></select><select><option>Any occupation</option><option>Farmer</option><option>Student</option></select><select><option>Any income range</option><option>Below ₹2.5 lakh</option></select><select><option>All categories</option><option>Agriculture</option><option>Healthcare</option></select></div><div className="scheme-grid">{schemes.map(s=><SchemeCard s={s} key={s.name}/>)}</div></section>
 <section className="eligibility"><div className="elig-copy"><span className="section-tag">ELIGIBILITY CHECKER</span><h2>Find your <em>potential benefits.</em></h2><p>Answer a few simple questions. We’ll explain why schemes may match — never a guaranteed approval.</p><div className="disclaimer"><Info size={18}/><span>Vaani-Setu gives AI-generated guidance. Always confirm details with the official portal.</span></div></div><div className="stepper"><div className="step-label">STEP {step} OF 6 <span>{["Basic information","Location","Occupation","Income","Family information","Requirements"][step-1]}</span></div><div className="progress"><i style={{width:`${step/6*100}%`}}/></div><label>{step===1?"What is your age?":step===2?"Which state do you live in?":step===3?"What best describes your occupation?":"Tell us a little more"}</label><input placeholder={step===1?"e.g. 32":"Choose or type your answer"}/><div className="step-actions"><button className="small-btn" disabled={step===1} onClick={()=>setStep(s=>s-1)}>Back</button><button className="small-btn primary" onClick={()=>step===6?notify("Your potential benefits are ready below."):setStep(s=>s+1)}>{step===6?"See matches":"Continue"}<ArrowRight size={15}/></button></div></div></section>
 <section className="documents"><div className="docs-card"><div className="docs-header"><div className="icon-box bg-orange-50 text-saffron"><FileText/></div><div><span className="section-tag">APPLICATION READY</span><h2>Know what you need <em>before you apply.</em></h2></div></div><div className="doc-grid"><div><p className="text-sm font-bold text-ink">PM-KISAN checklist</p><p className="mt-1 text-sm text-slate-500">5 of 7 documents ready</p><div className="doc-progress"><i/></div></div><div className="checks">{["Aadhaar Card","Income Certificate","Bank Account Details","Residence Certificate","Passport-size photograph","Land ownership record"].map((x,i)=><p key={x}><span className={i<5?"checked":""}>{i<5&&<Check size={13}/>}</span>{x}</p>)}</div></div><div className="mt-6 flex gap-3"><button className="small-btn" onClick={()=>notify("Checklist download prepared.")}><Download size={15}/> Download checklist</button><button className="small-btn" onClick={()=>notify("Saved for later in this demo.")}><Save size={15}/> Save for later</button></div></div></section>
 <section className="timeline"><div className="center intro"><span className="section-tag">CLEAR NEXT STEPS</span><h2>From guidance to <em>citizen action.</em></h2></div><div className="timeline-row">{["Check eligibility","Prepare documents","Visit official portal","Complete application","Track application status"].map((s,i)=><div className="time" key={s}><span>{i+1}</span><h3>{s}</h3><p>{i===2?"Use official sources to continue.":"Clear, simple guidance at every step."}</p></div>)}</div><div className="warning"><ShieldCheck size={19}/><b>Always verify application details and eligibility on the official government portal.</b></div></section>
 <section id="about" className="architecture"><div><span className="section-tag">TRUSTED BY DESIGN</span><h2>From one conversation to <em>actionable guidance.</em></h2><p className="lead">A responsible AI flow designed to make public services easier to understand — without replacing official verification.</p></div><div className="arch-flow">{["Citizen","Voice input","Multilingual understanding","Profile & intent extraction","Scheme matching engine","Trusted knowledge base","Personalized explanation","Documents + next steps","Citizen action"].map((x,i)=><div key={x} className="arch-node"><span>{String(i+1).padStart(2,"0")}</span>{x}{i<8&&<i/>}</div>)}</div></section>
 <section className="impact"><div><span className="section-tag">BUILT FOR THE LAST MILE</span><h2>Designed to <em>scale with trust.</em></h2><p className="lead">A more accessible doorway to the public services citizens already deserve.</p></div><div className="impact-grid">{[["Voice-first","Speak, don’t search"],["Multilingual","Language should not limit access"],["Personalized","Guidance made relevant"],["Action-oriented","From discovery to next step"]].map(([n,d])=><div className="impact-card" key={n}><b>{n}</b><p>{d}</p></div>)}</div></section>
 <section id="faq" className="faq"><div className="center intro"><span className="section-tag">FAQ</span><h2>Questions, answered <em>simply.</em></h2></div><div className="faq-list">{faqs.map((q,i)=><button className="faq-item" onClick={()=>setFaq(faq===i?null:i)} key={q}><span>{q}</span><ChevronDown className={faq===i?"rotate":""}/>{faq===i&&<p>{i===0?"Vaani-Setu is a voice-first AI guide that helps citizens discover and understand potentially relevant government schemes.":i===3?"No. Results are potential matches based on what you share. Eligibility and application decisions always rest with the official authorities.":"It uses structured scheme information and the context you provide to give simple, action-oriented guidance."}</p>}</button>)}</div></section>
 <footer><div><a className="brand" href="#home"><span className="brandmark"><Volume2 size={18}/></span>VAANI-SETU</a><p>One Conversation. Every Government Benefit.</p></div><div className="footerlinks"><a href="#home">Home</a><a href="#schemes">Schemes</a><a href="#how">How it works</a><a href="#faq">FAQ</a><a href="#">Privacy</a></div><p className="finale">CodeFusion 2026 — Grand Finale<br/><small>Independent prototype. Not an official government website.</small></p></footer>{loginOpen&&<div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="login-title"><div className="login-modal"><button className="modal-close" onClick={()=>setLoginOpen(false)} aria-label="Close login"><X size={19}/></button><div className="login-icon"><UserRound size={24}/></div><span className="section-tag">WELCOME TO VAANI-SETU</span><h2 id="login-title">Your guidance, <em>saved securely.</em></h2><p>Sign in to save scheme matches and document checklists on this device.</p><label>Your name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()} placeholder="Enter your name"/><button className="cta modal-submit" onClick={login}>Continue to Vaani-Setu <ArrowRight size={17}/></button><small>This is a prototype login. No personal data is sent or stored.</small></div></div>}{toast&&<div className="toast"><Check size={17}/>{toast}</div>}
 </main> }
